"""empty message

Revision ID: 571ef3461082
Revises: fe20085ce2ff
Create Date: 2019-04-20 09:24:04.471841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571ef3461082'
down_revision = 'fe20085ce2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'article_id')
    # ### end Alembic commands ###
